# SWeat 파이썬 W2-1 Homework

강의 후 과제 자료입니다

## 1. 서울시 인구 통계 분석: CSV 파일 처리하기
<a href="./W1-1_homework.ipynb">지난 차시 과제</a>에 함께 첨부되어 있습니다.

## 2. 연습 문제1
````{admonition} 연습 문제 1

넘파이를 사용하여 다음과 같은 행렬을 만든다.

```
10 20 30 40
50 60 70 80
```
````

In [3]:
import numpy as np

In [24]:
np.array([
    [10, 20, 30, 40,],
    [50, 60, 70, 80,]
])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3. 연습 문제 2
````{admonition} 연습 문제 2

다음 행렬과 같은 행렬이 있다.

```
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
````

In [31]:
m = np.array([
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14]
])

print(m[1][2])
print(m[2][4])
print(m[1, 1:3])
print(m[1:3, 2])
print(m[0:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


## 4. 연습 문제 3

````{admonition} 연습 문제 3

다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
````

In [37]:
x = np.array([
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20
])

print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## 5. Numpy 연습문제
````{admonition} 연습 문제 3.2.1

지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.

```
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])
```
````


In [23]:
upper = np.hstack((np.zeros((3, 3)), np.ones((3, 2))))
lower = np.linspace(1, 15, 15).reshape((3, 5)) * 10

result = np.tile(np.vstack((upper, lower)).T, 2).T
result

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])